---
- name: create directories
  file:
    path: {{ item }}
    owner: "{{ docker_uid }}"
    mode: 0664
    state: directory
  with_items:
    - "{{ appdata_path }}/letsencrypt/config/nginx/site-confs"
    - "{{ appdata_path }}/letsencrypt/config/nginx/proxy-confs"

- name: install nginx default config for letsencrypt
  copy:
    src: "{{ playbook_dir }}/files/nginx-confs/nginx-default"
    dest: "{{ appdata_path }}/letsencrypt/config/nginx/site-confs/default"
    owner: "{{ docker_uid }}"
    mode: 0664
  register: nginx_default

- name: decide whether to restart letsencrypt container
  set_fact:
    restart_le: True
  when:
    - nginx_default.changed