---
- name: create directories
  file:
    path: "{{ nginx_configs_conf_dir_main }}/{{ item }}"
    owner: "{{ main_uid }}"
    mode: 0664
    state: directory
  with_items:
    - "site-confs"
    - "proxy-confs"

- name: install default nginx config for letsencrypt
  copy:
    src: "{{ nginx_configs_conf_dir_local }}/nginx-default"
    dest: "{{ nginx_configs_conf_dir_main }}/site-confs/default"
    owner: "{{ main_uid }}"
    mode: 0664
  register: nginx_default

- name: decide whether to restart letsencrypt container
  set_fact:
    restart_le: True
  when:
    - nginx_default.changed