---

- name: install default nginx config
  include: default-config.yml

- name: install nginx subdomain configs
  include: subdomains.yml
  when:
    - item.rp_type == "subdom"
  with_items:
    - "{{ containers }}"

- name: install nginx subfolder configs
  include: subfolders.yml
  when:
    - item.rp_type == "subfol"
  with_items:
    - "{{ containers }}"

- name: restart letsencrypt container if configs changed
  command: docker restart le
  when: restart_le