---

- name: install enabled nginx subdomain configs
  copy:
    src: "{{ nginx_configs_conf_dir_local }}/subdomains/{{ item.service_name }}.conf"
    dest: "{{ nginx_configs_conf_dir_main }}/site-confs/{{ item.service_name }}.conf"
    owner: "{{ main_uid }}"
    mode: 0664
  when: 
  - item.active == true 
  - item.nginx_configs_rp_enabled == true
  register: nginx_subd

- name: remove disabled subdomain nginx configs
  file:
    path: "{{ nginx_configs_conf_dir_main }}/site-confs/{{ item.service_name }}.conf"
    state: absent
  when: 
    - item.active == false or item.nginx_configs_rp_enabled == false
  register: nginx_rem_subdom

- name: decide whether to restart letsencrypt container
  set_fact:
    nginx_configs_restart_le: True
  when: >
    nginx_subd.changed
    or nginx_rem_subdom.changed

# - name: restart letsencrypt container if configs changed
#   command: docker restart le
#   when: restart_le