---

- name: install enabled nginx subdomain configs
  copy:
    src: "{{ playbook_dir }}/files/nginx-confs/subdomains/{{ item.service_name }}.conf"
    dest: "{{ appdata_path }}/letsencrypt/config/nginx/site-confs/{{ item.service_name }}.conf"
    owner: "{{ docker_uid }}"
    mode: 0664
  when: 
  - item.active == true 
  - item.rp_enabled == true
  register: nginx_subd

- name: remove disabled subdomain nginx configs
  file:
    path: "{{ appdata_path }}/letsencrypt/config/nginx/site-confs/{{ item.service_name }}.conf"
    state: absent
  when: 
    - item.active == false or item.rp_enabled == false
  register: nginx_rem_subdom

- name: decide whether to restart letsencrypt container
  set_fact:
    restart_le: True
  when: >
    nginx_subd.changed
    or nginx_rem_subdom.changed

# - name: restart letsencrypt container if configs changed
#   command: docker restart le
#   when: restart_le