---

- name: install enabled nginx subfolder configs
  copy:
    src: "{{ playbook_dir }}/files/nginx-confs/subfolders/{{ item.service_name }}.conf"
    dest: "{{ appdata_path }}/letsencrypt/config/nginx/proxy-confs/{{ item.service_name }}.conf"
    owner: "{{ docker_uid }}"
    mode: 0664
  when: 
  - item.active == true 
  - item.rp_enabled == true
  register: nginx_subfol

- name: remove disabled subfolder nginx configs
  file:
    path: "{{ appdata_path }}/letsencrypt/config/nginx/proxy-confs/{{ item.service_name }}.conf"
    state: absent
  when: 
    - item.active == false or item.rp_enabled == false
  register: nginx_rem_subfol

- name: decide whether to restart letsencrypt container
  set_fact:
    restart_le: True
  when: >
    nginx_subfol.changed
    or nginx_rem_subfol.changed